# Generated by Django 3.2.5 on 2021-07-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('questions', '0001_initial'),
        ('quizes', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='quiz',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz'),
        ),
    ]
