# Generated by Django 3.2.5 on 2021-07-01 16:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('quizes', '0001_initial'),
        ('results', '0001_initial'),
        ('questions', '0002_subquestion_quiz'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='result',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.result'),
        ),
        migrations.AddField(
            model_name='question',
            name='quizes',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='quizes.quiz'),
        ),
        migrations.AddField(
            model_name='choice',
            name='question',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='questions.question'),
        ),
    ]
