# Generated by Django 2.2.5 on 2021-06-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('results', '0002_result_student'),
        ('questions', '0002_auto_20210627_0119'),
    ]

    operations = [
        migrations.CreateModel(
            name='SubQuestion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('attempted_Choice', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Choice')),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='questions.Question')),
                ('result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='results.Result')),
            ],
        ),
    ]
