# Generated by Django 2.2.5 on 2021-06-28 22:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('quizes', '0002_quiz_creator'),
        ('questions', '0003_subquestion'),
    ]

    operations = [
        migrations.AddField(
            model_name='subquestion',
            name='quiz',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='quizes.Quiz'),
            preserve_default=False,
        ),
    ]
