# Generated by Django 2.2.5 on 2021-06-26 19:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('topic', models.CharField(max_length=30)),
                ('total_score', models.FloatField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
